Develop
xcixor/my-ride pull request #5
Opened 2018-06-21 06:27 UTC by xcixor

#### Purpose of the PR
* Creates all the features required by a driver and a passenger to use the application
#### Tasks to be complete
* Show all rides
* Show the details of a ride
* Show the status of a ride
* Show ride history for both the driver and the passenger
* Enable ride requesting
* Enable ride confirmation (reject/accept)
#### Manual testing
* Navigate to the repo's main page via  [this link](https://github.com/xcixor/my-ride)
* Under the repo's name copy the clone's url
* Open a terminal and navigate to where you want the repo to be downloaded
* Type git clone 'the url you copied above' and press enter to download
* Checkout to the branch develop
* Navigate to the UI folder
* Open the index file with your favorite browser
* Start running!
* To preview on mobile in chrome inspect the page and the browser's inspection tool will provide 
   previews for various screens
* Or preview the site [here](https://xcixor.github.io/my-ride/)
#### Relevant pivotal tracker stories 
[user should be able to view available rides ](https://www.pivotaltracker.com/n/projects/2179559)
[User should be able to see the details of a ride and make a request. ](https://www.pivotaltracker.com/n/projects/2179559)
[A driver should be able to see the status of a ride](https://www.pivotaltracker.com/n/projects/2179559)
[A user should be able to see ride history ](https://www.pivotaltracker.com/n/projects/2179559)

2018-06-21 13:11 UTC, JoshuaOndieki commented on UI/driver_dashboard.html
>              <span style="font-size:30px;cursor:pointer; padding: 20px;" onclick="openNav()">&#9776;</span>
Inline CSS :x:

2018-06-21 13:13 UTC, JoshuaOndieki requested changes

2018-06-21 13:13 UTC, JoshuaOndieki commented on UI/driver_dashboard.html
> +            <span style="font-size:30px;cursor:pointer; padding: 20px;" onclick="openNav()">&#9776;</span>
Inline CSS :x:

2018-06-21 14:26 UTC, xcixor commented on UI/driver_dashboard.html
> +            <span style="font-size:30px;cursor:pointer; padding: 20px;" onclick="openNav()">&#9776;</span>
let me check it out

2018-06-21 15:01 UTC, artorious commented
Hi, As you fix your `CSS` take a look at whats causing the overflow of some elements in small screen.
Earlier versions didn't have this bug. 
 
![screenshot_2018-06-21-17-51-28](https://user-images.githubusercontent.com/15730750/41727341-cc7b6a76-757c-11e8-9604-9537cb71ff6f.png)
![screenshot_2018-06-21-17-51-56](https://user-images.githubusercontent.com/15730750/41727342-ccdf18aa-757c-11e8-92d5-777f735cdf63.png)
![screenshot_2018-06-21-17-52-10](https://user-images.githubusercontent.com/15730750/41727344-cd58fcc4-757c-11e8-931c-6fee945d8d07.png)
![screenshot_2018-06-21-17-52-18](https://user-images.githubusercontent.com/15730750/41727346-cdaa6956-757c-11e8-98b6-da7e1dc8f57b.png)

2018-06-22 17:43 UTC, xcixor commented
#### Purpose of the PR
* Implement LFA feedback
#### Tasks to be complete
* Create user profile page
* Add more details about a ride - number plate
* Public driver profile with contacts
* passenger sees ride status accept or reject
#### Screenshots
##### User profile
![feed1](https://user-images.githubusercontent.com/22756288/41790136-3c4f292c-765a-11e8-8de9-78905348b758.png)

##### Link to view more driver details
![feed2](https://user-images.githubusercontent.com/22756288/41790193-67a2d420-765a-11e8-872a-94fc2f469c56.png)

##### More ride's details
![feed5](https://user-images.githubusercontent.com/22756288/41790899-b95f06c4-765c-11e8-8742-4f0692a631f5.png)


##### Driver's profile
![feed3](https://user-images.githubusercontent.com/22756288/41790212-743eff9c-765a-11e8-9bdc-ef2735cf97f0.png)

##### Ride status
![feed4](https://user-images.githubusercontent.com/22756288/41790297-c23c532a-765a-11e8-83bd-67f96d3254d8.png)

2018-06-22 18:05 UTC, JoshuaOndieki commented
You could have opened a new PR for these changes specifically requested by the LFA.
Anyway, since you have already pushed to this PR and as I can see all requested features have been implemented, you're good to go :+1:

2018-06-22 18:35 UTC, merged